### ISSUE TITLE
TWEWY Mingle mode stuck on "Ending Communications" after idling for half an hour

### ISSUE THREAD

**Issue by Stevoisiak** [melonDS-emu/melonDS#1111]
**Issue**:
In _The World Ends With You_, after leaving "Mingle Mode" running for half an hour with frame limit off to grind Mingle XP, the game gets stuck on "Ending communications" when trying to exit.

**Steps to reproduce**:
1. Play until you unlock Mingle Mode. ([Save file provided](https://github.com/Arisotura/melonDS/files/6519357/World.Ends.With.You.-.Mingle.Save.Bug.zip))
2. Load the game, then open the main menu by tapping the phone icon in the top right.
3. Tap the "Mingle" button, then tap "Start".
4. In melonDS, open "System" disable "Limit framerate", and leave the game running for around half an hour. (Or use [the attached savestate](https://github.com/Arisotura/melonDS/files/6519357/World.Ends.With.You.-.Mingle.Save.Bug.zip))
5. Click "Finish" to try and exit.

**Expected result**:
Communications end, game is saved.

**Actual result**:
Game gets stuck on "Ending communications".

**System info**:
- melonDS 0.9.2
- Windows 10 Pro Version 1909
- AMD Ryzen 5 5600X
- ROM MD5: 3BFC95753B37C97A6D30018630048A51

**Screenshot**:
!["Ending communications."](https://user-images.githubusercontent.com/1330770/119065428-7cd7dd80-b9ab-11eb-987c-520622b4f138.png)

**Comment by RSDuck** [comment]
if I had to guess this is could be the same issue as https://github.com/Arisotura/melonDS/issues/739

**Comment by Stevoisiak** [comment]
The issue occurs in No$GBA as well.

**Comment by RSDuck** [comment]
I looked into it with the savestate you provided and it's definitely the same underlying issue as #739

**Comment by KostaSaizo7** [comment]
Probably fixed by https://github.com/melonDS-emu/melonDS/pull/1516 and 0a1fb5ae50d2c9941a7c5e6bce5f9870b6e2c1b3 ?

![The World Ends with You](https://user-images.githubusercontent.com/39852873/192130630-78167fd5-2cb0-4c16-b1ce-8e1958a85498.png)
![The World Ends with You b](https://user-images.githubusercontent.com/39852873/192130637-95d00584-7309-4306-8a7f-a92cbb0ef142.png)
![The World Ends with You c](https://user-images.githubusercontent.com/39852873/192130638-765aefa8-e5a9-4d89-b9c7-3daeb7774d5e.png)
