### ISSUE TITLE
Issues with command line startup archives and East Asian filenames

### ISSUE THREAD

**Issue by crashGG** [melonDS-emu/melonDS#1556]
1. Start the 7z archives(nointro) at the command line, the program will exit.for example:
  melonDS.exe “Mario Kart DS (USA) (En,Fr,De,Es,It).7z”
 But dragging this file directly to the opened melonds window works fine.

2. Start the roms with East Asian filenames at the command line, it doesn't work.for example:
  melonDS.exe “超时空之轮V4(汉化).nds”
 But dragging this file directly to the opened melonds window works fine.
<img width="220" alt="2022-11-06_102440" src="https://user-images.githubusercontent.com/80488411/200159262-400cfe4e-a4cd-4b14-9ee7-7665ecf98476.png">

OS: win10 1809 (Simplified Chinese)
melonDS: 0.9.5

**Comment by patataofcourse** [comment]
interesting- i'll look into it

**Comment by patataofcourse** [comment]
okay so

> 1. Start the 7z archives(nointro) at the command line, the program will exit.for example:
>    melonDS.exe “Mario Kart DS (USA) (En,Fr,De,Es,It).7z”
>    But dragging this file directly to the opened melonds window works fine.

for this you probably want to use the `-a / --archive-file` parameter
for example if you wanna open "Mario Kart DS.nds" inside that .7z file, you run
`melonDS.exe “Mario Kart DS (USA) (En,Fr,De,Es,It).7z” -a "Mario Kart DS.nds"`
change that to whatever name the .nds file inside that .7z has

> 2. Start the roms with East Asian filenames at the command line, it doesn't work.for example:
>    melonDS.exe “超时空之轮V4(汉化).nds”
>    But dragging this file directly to the opened melonds window works fine.

looking into it rn, there's a chance that it's Windows fucking stuff up, because i can't reproduce this issue on Linux. if that's the case i don't think there's a lot we can do, sadly. it's probably a case of windows interpreting the UTF-8 string with its own encoding (which doesn't support a lot of Unicode characters, including non-Latin alphabets). there's probably a way to convert it though so not all hope is lost :D

**Comment by crashGG** [comment]
But dragging these files directly to the opened melonds window ,they work fine.really weird
