### ISSUE TITLE
[Feature request] Switch Screen-Emphasis hotkey

### ISSUE THREAD

**Issue by ghost** [melonDS-emu/melonDS#1565]
In DeSmuMe I play with vertical screen layout, with 1 screen being bigger than the other. There is a hotkey called "Swap LCD" that toggles either Top or Bottom screen being the bigger one (or being 'emphasized' in MelonDS terms).

In MelonDS there is no button for this. Yes I can exit fullscreen, go into the dropdown, and change the emphasis, each time I want to swap it. But a hotkey would be great. I cant be the only one who wants this.

Thank you for considering.

**Comment by sandwichwater** [comment]
in addition to this , having an auto emphasize mode for single screen would be great too , there is a mode called "auto" which automatically emphasizes the main screen being used (most of the time) but in single screen it doesnt auto emphasize for some reason , you need to manually swap screens to change emphasis 

having an auto mode as an addition to the existing modes to instead of an emphasis mode itself would solve both of these problems , as it wouldnt lock emphasis to a single screen leaving users to have to manually swap emphasis and would let single screen mode work like the current auto mode

**Comment by mariomadproductions** [comment]
@sandwichwater why downvote? 🤔

**Comment by sandwichwater** [comment]
@mariomadproductions eh i wasnt having a good day so when i saw that the person who posted this downvoted my solution to fix both this and another glaring similar issue i downvoted them back out of spite or some similar reason . probably shouldnt have , thats on me , though i still dont know why they downvoted me in the first place seeing as i havent refuted or disagreed with their suggestion

**Comment by fsmid** [comment]
You already made a separate issue for this, and now you highjack this thread to ask for the same thing again.

**Comment by sandwichwater** [comment]
i just added a suggestion that builds off of your original idea in hopes it will be seen more as the first time nothing happened with it , which again , would solve both issues . i dont know what the point of discussions for a project like this are if you cant build off of others suggestions , if thats considered hijacking then yea , me and many many others are so incredibly guilty of hijacking every single thread we commented on . you couldve simply asked me to move my suggestion to another place instead of silently downvoting without elaborating the first time and i gladly wouldve done so
