### ISSUE TITLE
Android version - Support 

### ISSUE THREAD

**Issue by GreenShadows** [melonDS-emu/melonDS#1573]
Why is there official support for platforms with relatively few users like linux but not android which has hundreds of millions of users?

Unfortunately the version adapted by third parties is completely outdated and without any support.

**Comment by beta215** [comment]
I guess there would be an Android version if someone could and wanted to work on it. There's nothing stopping people from doing it - not even stopping you. It's not like this was closed source software anyway, so feel free to contribute and make it happen.

**Comment by CasualPokePlayer** [comment]
Android is one of if not the most develop hostile platforms out there. The OS is very restrictive for how apps can operate, and a complete pain to debug for due every app being a fork of the main java process among other reasons. The userbase is also generally not flattering, usually being the worst to give tech support to. Standard Linux distros however are the exact opposite, where the OS is extremely friendly to developers and the users are usually not a pain to help.

Of course anyone can go add Android support to melonDS, but it shouldn't be surprising that Android support is very low priority for most developers in general.

**Comment by patataofcourse** [comment]
Short answer - because we don't want to and we don't have to. Demands are fucking rude, if you want something done so bad do it yourself.

**Comment by GreenShadows** [comment]
> I guess there would be an Android version if someone could and wanted to work on it. There's nothing stopping people from doing it - not even stopping you. It's not like this was closed source software anyway, so feel free to contribute and make it happen.

I'm not a dev. This is the same as a doctor telling someone who is sick to go and study medicine so they can self-diagnose. 

I'm not a dev. This is the same as a doctor telling someone who is sick to go and study medicine so they can self-diagnose.

I think CasualPokePlayer's answer was the most intent on clarifying rather than just coming up with the arrogance of "because I don't want to"

**Comment by patataofcourse** [comment]
melonDS is free, unpaid work that is done as a hobby project. You are not paying for melonDS, and the developers don't get paid for their work. In exchange, you get melonDS for free. But you aren't the boss of anyone and going around open source projects making demands that you don't really understand will only make you enemies. 

> Why is there official support for platforms with relatively few users like linux but not android which has hundreds of millions of users?

This specifically feels unnecessary and mean, honestly, kind of feels like you're saying having less users means Linux is irrelevant in all regards. And, to be fair, it's not like Linux is exactly niche- tons of people use it.

(Also, it's not like Android support hasn't been asked before, and making a brand new issue for this stuff just shows that you haven't digged before asking. This place is for bugs and feature requests, so if you just wanted to know why this was you probably should've went to the forum, the IRC, or the Discord)

As someone who's very active in a few hobby communities (specifically a modding community), it's really disrespectful and angering when someone just asks "pls do this" like it doesn't take hard work. Specifically when it's been confirmed that it's not gonna happen for the time being.

Generally, if someone wants to port melonDS to android, or update the fork, they will. Nobody wants to, so they don't do it.

Also, needing medical attention and wanting to play games on your phone are not comparable. Medical attention is kind of a need and a human right. Please don't make that comparison again, it just... isn't as much of a gotcha as you think it is

**Comment by beta215** [comment]
> > I guess there would be an Android version if someone could and wanted to work on it. There's nothing stopping people from doing it - not even stopping you. It's not like this was closed source software anyway, so feel free to contribute and make it happen.
> 
> I'm not a dev. This is the same as a doctor telling someone who is sick to go and study medicine so they can self-diagnose.
> 
> I think CasualPokePlayer's answer was the most intent on clarifying rather than just coming up with the arrogance of "because I don't want to", So Thank you

As far as I know, you're not gonna die if melonDS isn't ported to Android. You can learn to do it yourself and contribute to this great project, showing your gratitude. I don't think you'll have the time to learn medicine fast enough if you're sick, yet you'll definitely have the time to learn programming before you die. And you'll give something amazing to people.

**Comment by RSDuck** [comment]
> For someone who is a developer your line of logical reasoning is a little off.

Their reasoning is not off by a bit.

There might be different reasons why people contribute to melonDS, but one thing is clear: melonDS is not a business, we don't seek to maximise our shareholder's profits, where the logical thing would indeed be to target the largest user bases.

Thus while we also want to make a good piece of software for the community to use, we aren't being paid for this, so when we do this, it's entirely on our own terms. And as already discussed here Android developement is quite pitiful, nor a speciality of us. At the same time a lot of developers here use Linux as their main operating system and almost all of the GUI code is shared across Windows, Linux and macOS thanks to QT.

Or another example I like doing Nintendo Switch homebrew, which is why melonDS has an official Switch port.

These are the criteria on why we support one platform, but not some other.

At last regarding the reactions you have got, I have to add some context. From the experience of other projects which do have Android ports and requests for a Android port, "Android users" are a bit infamous for not showing much respect for voluntary work of developers. I don't think what you wrote was disrespectful, but it does show a misunderstanding of how things run here (or most everywhere in the open source space).
