### ISSUE TITLE
Cannot open libslirp.so.0

### ISSUE THREAD

**Issue by LeololDB** [melonDS-emu/melonDS#1611]
When just executing melonDS, I get this error
```./melonDS: error while loading shared libraries: libslirp.so.0: cannot open shared object file: No such file or directory```
That's been the 3rd DS emulator I tried ('-' )
I know, Linux is annoying.

**Comment by nadiaholmquist** [comment]
You need to install libslirp. The package for it might be named a bit differently depending on which distro you're using so you'll have to search for that yourself.

Alternatively if you don't want to install libraries to run it, you can use the flatpak for melonDS.

**Comment by LeololDB** [comment]
Thanks!
The message indicates that the program is unable to find the library file libslirp.so.0.
To install it on Debian-like systems, we can run
```
sudo apt-get install libslirp0 to install the library.
```

Also, for other people having the problem, if the library is already installed but the program is unable to find it, you may need to add the directory where the library is located to the LD_LIBRARY_PATH environment variable.

_You can also try running the command ldd <path to melonDS binary> to see which libraries it is trying to load and check if all of them are available._

**Comment by Brian151** [comment]
I would argue that this is _not_ completely resolved.

I recently purchased a laptop, and for a few reasons, I installed debian on it. 
MelonDS is naturally on the list of software I would like to be able to run.

So, I downloaded the pre-compiled release
Nothing happens when I run it from the file explorer GUI, just get "command not found"
If I run it in terminal, and **only** if I run it in terminal, the actual proper error message appears

If an external dependency is going to be required but not necesarrily included, this fact should be presented up front. 
And I feel that there was a complete failure to communicate this fact inr elation to the pre-compiled binary.

1. As a _user_ , I am not necesarrily going to read the _developer_ instructions
2. A program should not just fail silently like this, that error should be **in my face** and not something I only get if running from command line
3. The readme and website did not inform me there's an external dependency

My suggestions would be
- update readme & website to **explicitly** mention the requirement of libslirp in the pre-compiled linux binary
- at least attempt to propogate the missing library error to a popup or other **obnoxious** means of displaying a warning/error
- include with the pre-compiled linux binary a README.txt to the same effect

Sorry to be, _that_ guy, but I do feel this is something which should be addressed...

**Comment by nadiaholmquist** [comment]
> update readme & website to explicitly mention the requirement of libslirp in the pre-compiled linux binary

This should probably be done, and if I had access to editing the website I would have made it link to the page for melonDS on flathub, because shipping bare Linux binaries isn't really a good idea in the first place.

> at least attempt to propogate the missing library error to a popup or other obnoxious means of displaying a warning/error

Unless we introduce some sort of launcher process or open the libslirp library at runtime, there's not really a way to do this. Not properly communicating failures to launch programs is a problem with Linux desktop environments themselves. On Windows, if you were in this same situation there would be a dialog box telling you that there's a missing DLL, but Linux desktops have no such mechanism.

Development builds are also shipped as AppImages, and ideally we will also release one on the site when the next stable version is released.

> include with the pre-compiled linux binary a README.txt to the same effect

Doesn't seem like a bad idea, though if including anything maybe it'd be better just including a copy of libslirp.

**Comment by Brian151** [comment]
include libslirp : 
i was gonna suggest "just include libslirp" but that leans in a particular direction...

appimages : 
appimages do seem interesting. may or may not use that for my own projects when/if i get to linux builds, i just prefer not bloating installs/downloads by duplicating all this code which really should be installed globally. [in an ideal world...]

tell me the actual problem when it crashes:
even windows programs can encounter less than useful error messages for this sorta thing. i actually recently-ish had an issue with minecraft, since they just love making breaking changes to the game >.> error message: "texture not found" , actual problem : "atlas paths not configured correctly"... , that was fun! /s

no worries! i figured that was a possiblity!
