### ISSUE TITLE
LAN multiplayer not working (Mario Kart DS)

### ISSUE THREAD

**Issue by ImSapphire** [melonDS-emu/melonDS#2202]
When trying to join other LAN players' groups, the game shows an 'An error has occurred' popup after 1-2 seconds. I'm using WireGuard to create a tunnel between my network and my friend's.

Here is a screenshot of my screen (left) and my friend's (right):
![Screenshot_20241118_160219](https://github.com/user-attachments/assets/199e0397-c3c8-46c2-af99-3a7b2349a916)

**Comment by nadiaholmquist** [comment]
Virtual LANs are not supported currently, you'll have to wait for proper netplay to do that. You're only supposed to use this with a real local network.

**Comment by JesseTG** [comment]
The reason that local wireless emulation only works over LAN is that DS games were usually written to expect very low ping (~5ms). Reasonable when sitting next to someone with their own DS, not so much across long distances.

For Mario Kart in particular, you should use WFC emulation instead -- it works as expected because back in the day it had to go over the Internet too. Otherwise, you'll have to settle for cheap plane tickets
