### ISSUE TITLE
Inazuma Eleven (2) Multiplayer

### ISSUE THREAD

**Issue by thormented** [melonDS-emu/melonDS#236]
When using any options on the connect screen, I can setup host and try to connect to the host using melonds, but it inevitably fails after a few seconds.

All three of Inazuma Eleven, Inazuma Eleven 2:Firestorm and Inazuma Eleven 2:Blizzard have this issue.

**Comment by Comlud** [comment]
Same thing for Super Dodgeball Brawlers. The host and client can see each other, start a connection, but then it fails. This should work, have done it before on a ds. Have tried multiple roms, but no difference.

Can it be the timing that fails?

NSMB works, but not locally between to computers, because it's too slow. With an ethernet cable, it kinda works, but it's really laggy. Maybe this is the case for Super Dodgeball Brawlers, that it's too slow or something, even though the host and client both are on the same computer?

**Comment by KostaSaizo7** [comment]
This still happens with the latest local wifi branch. I am pointing this out because, after trying more than 20 games, the Inazuma games are the only ones that fail to connect.

**Comment by KostaSaizo7** [comment]
> Same thing for Super Dodgeball Brawlers. The host and client can see each other, start a connection, but then it fails. This should work, have done it before on a ds. Have tried multiple roms, but no difference.

Super Dodgeball Brawlers works fine with the latest local wifi branch :)

![image](https://user-images.githubusercontent.com/39852873/190319863-35965bd0-76e7-4aa1-8536-1811c5e2b6ef.png)

**Comment by KostaSaizo7** [comment]
Inazuma 1+2 are fixed by 1f170a36e18e550dbbe3e7160cb4d15ab17ffefb
