### ISSUE TITLE
[NTR-CLPPv00/NTR-CLPEv02] wifi: !! unusual TXSLOT_CMD bits set C000 

### ISSUE THREAD

**Issue by wertercatt** [melonDS-emu/melonDS#485]
When attempting to connect roms of Club Penguin: Elite Penguin Force together with melonDS, the message in the title is constantly spat out to stderr and the games experience a connection issue soon after.
Note that the European and American versions of the game are able to communicate on real hardware, so that isn't related to the issue.

**Comment by Arisotura** [comment]
that seems to happen when communication fails. known issue.

**Comment by wertercatt** [comment]
Is communication failure common when the device can't run both copies of melonDS at full speed?

**Comment by Arisotura** [comment]
it would happen more when the two instances don't run at the same speed, or when you have the framerate limiter on

**Comment by InfiniteWorldLegacy** [comment]
I have the same problem when trying to trade pokemon. But I don't understand why that happens, because I have tested it in three different computers, and only in one the issue rises. The other two computers worked fine when trading. What could be possibly be wrong with my computer? I use a Windows10, laptop gamer.

**Comment by InfiniteWorldLegacy** [comment]
Well... I believe I've found a solution for my problem. On my Laptop gamer, I gotta set my Windows power plan to High Performance. For some weird reasons, that prevents the second window of Melon DS 0.4 from getting problems with ''wifi: !! unusual... etc etc''
I was using Balanced power plan, since my laptop gamer can handle games and emulators with ease, but for trading pokemon on it, High performance do the trick. I test it three times in a row, and it worked, I sure hope it's not coincidence... Anyways. Thanks a lot for your lovely emulator

**Comment by KostaSaizo7** [comment]
Fixed by https://github.com/melonDS-emu/melonDS/pull/1516
![Club Penguin Elite Penguin Force ](https://user-images.githubusercontent.com/39852873/192129561-9ab5e13b-107b-4f8d-a8c0-d99401da4260.jpg)
![Club Penguin Elite Penguin Force coach](https://user-images.githubusercontent.com/39852873/192129562-4f5044e8-7989-491b-ab71-56cc307444d5.jpg)
