### ISSUE TITLE
Game crashes when saving in pokemon white

### ISSUE THREAD

**Issue by AbsenceFlintIvy** [melonDS-emu/melonDS#739]
![Screenshot from 2020-09-03 19-34-37](https://user-images.githubusercontent.com/53026688/92186518-a3091d80-ee1c-11ea-94a8-f814ebf04172.png)

**Comment by RSDuck** [comment]
this bug is already known and a bit of a specter. Weren't eable to reproduce and/or pin it down by much, because it seems to occur after a long playtime and seemingly at random.

For reference this is what we already know:
- it's probably wifi related, because disabling the C-Gear allegedly prevents it from happening. Also there's a very similar bug happening in the Underground in Pokemon Diamond/Perl/Platinum, where wifi is enabled as well. Also it the console is spammed with rx buffer overflow messages (in both cases).
- the ARM7 state seems to be corrupted in some way, but not completely. 1. the wifi rx buffer is full. 2. the time is displayed wrong (as in the screenshot), 3. the game freezes once some specific (likely wifi related) thing is requested from the ARM7. In one savestate we received the game was still playable (including the touchscreen still working), but every action involving wifi (which includes saving in Pokemon Black/White), results in a freeze.

Welp!

**Comment by RSDuck** [comment]
this bug is due to wifi power saving not being properly implemented, which can lead to the ARM7 getting into an infinite loop.

**Comment by RSDuck** [comment]
this can still happen

**Comment by AbsenceFlintIvy** [comment]
big oof

**Comment by Priestyle** [comment]
Is there any workaround or temporary fix for this issue?

**Comment by RSDuck** [comment]
as already said, not enabling C-Gear should prevent this issue

**Comment by Priestyle** [comment]
Hey, thanks for the response. I just want to report that the gen 5 Pokemon games crash A LOT earlier on versions 9.1 and above. When I use the c-gear on 0.8.3 for multiplayer stuff (survey, entralink, etc.), it crashes maybe after 15 ~ 20 minutes as opposed to 9.1 & up crashing as early as 1 ~ 2 minutes (including freezing during saving).

**Comment by bhsmith90** [comment]
Been playing Pokémon Black and when I get to the Ferris wheel in Nimbasa City the screen goes black. Music plays but I can’t do anything. Wait for about 20 minutes and still no loading. It seems like this “cut scene” is vital to move forward so any help would be appreciated.

**Comment by orlp** [comment]
I can reproduce this with the error (wifi: RX buffer full) on Ubuntu with 0.9.2.

If it helps the developers I can provide a save state in which the bug has occurred.

**Comment by Icywastaken** [comment]
The cgear freezes too when i try to turn it off

**Comment by RSDuck** [comment]
what version of melonDS where you using when the freeze was first happening?

**Comment by Fallen-Feces** [comment]
(Using 0.9.3)
So this issue happened to me too however I was playing Blaze Black 2 Redux. I hadn't saved properly since before the first gym and beat the 2nd gym now with a bunch of save states up leading up to that point. My most recent states result in the exact same issue as what's shown at the beginning of this thread. Attempting to turn off the C-Gear also freezes the game. I found a state that doesn't seem to have a corrupted date and time on the save screen, however when attempting to save it gives me this.
![save state issue](https://user-images.githubusercontent.com/44452380/167227262-ff9dd224-7fc5-4750-852d-df4cbd31f3b7.PNG)
Turning off the C-Gear in this state does work, however it still results in the same error when trying to save. Unlike with the newest state, this one is also VERY prone to crashing MelonDS entirely. Even while writing this comment it crashed twice and after a while it actually just began to refuse to load the state and ends up crashing instantly when I try to.

**Comment by Fallen-Feces** [comment]
Is it known whether or not this issue was fixed in 0.9.4? Would love to be able to use C-Gear boosts in gen 5 again.

**Comment by nadiaholmquist** [comment]
It is fixed in 0.9.4.

**Comment by RSDuck** [comment]
* should be, if it still happens please notify me.

**Comment by mpurdie26** [comment]
currently playing black 2 and am experiencing the same issue during the force save at pokestar studios in which the game freezes. i’ve been using save states instead of saving in-game but i have another save state from the first few minutes of the game that does let me save. i can’t manually turn off the c-gear or it’ll freeze as well, but i tried a cheat that turns the c-gear off but alas i still couldn’t save. any idea how to fix this?

**Comment by RSDuck** [comment]
did you ran into the issue with 0.9.3 or 0.9.4?

**Comment by mpurdie26** [comment]
i believe 0.9.4, i’m playing through delta with their melon core

**Comment by mpurdie26** [comment]
definitely 0.9.4 and i'm still encountering this issue

**Comment by RSDuck** [comment]
can you give me a savestate where this issue is present?

**Comment by mpurdie26** [comment]
neither savestates nor save files are supported file types on Github, according to the message when I try uploading them. i've restarted the game, as well as tried other roms for Black 2, but the issue still arises once the game tries to make me force save

**Comment by nadiaholmquist** [comment]
Put it in a zip file or rename it, then you should be able to post it.

**Comment by mpurdie26** [comment]
[D0445296-1F08-4EB0-8074-35D785F2A906.zip](https://github.com/Arisotura/melonDS/files/9154607/D0445296-1F08-4EB0-8074-35D785F2A906.zip)
lol thank you so much for your patience i'm not the most experienced with emulators and such

**Comment by nadiaholmquist** [comment]
[D0445296-1F08-4EB0-8074-35D785F2A906.fixed.zip](https://github.com/Arisotura/melonDS/files/9154621/D0445296-1F08-4EB0-8074-35D785F2A906.fixed.zip)

Try this

**Comment by RSDuck** [comment]
based on the state of https://github.com/rileytestut/melonDS and information in the savestate you provided the melonDS version the delta melonDS core or however it is called uses is 0.9.1.

**Comment by mpurdie26** [comment]
oh wow okay, thank you both for your help. the new savestate seems to let me save in-game, so i appreciate the assistance. i'll open this issue with Delta as opposed to MelonDS if this problem arises in the future -- my apologizes for assuming i had the correct version

**Comment by nadiaholmquist** [comment]
From here on out, never turn on the C-Gear in the game until their melonDS port is updated.

**Comment by AaronPenders** [comment]
> [D0445296-1F08-4EB0-8074-35D785F2A906.fixed.zip](https://github.com/Arisotura/melonDS/files/9154621/D0445296-1F08-4EB0-8074-35D785F2A906.fixed.zip)
> 
> Try this

What exactly did you do to fix this bugged savestate? I'm currently facing similar issues as described above, namely (i) game freeze upon saving in-game, (ii) game freeze upon attempting to switch off c-gear, and most urgently (iii) black screen upon accepting Skyla's request to join her on her plane towards Lentimas town. From what i have read, all of these seem to be related to the c-gear interface?

-Currently playing on the Android app store beta melonds 1.7.0 PS
-Can provide devs with playable savestates just before the issue occurs

**Comment by RSDuck** [comment]
yes this is the same issue. Nadia has put together a tool for fixing savestates: https://gist.github.com/nadiaholmquist/a90e5810ddb27544a9eb967e4448636c

Note that if you enable the C gear again, the freeze can also happen again.

**Comment by AaronPenders** [comment]
> yes this is the same issue. Nadia has put together a tool for fixing savestates: https://gist.github.com/nadiaholmquist/a90e5810ddb27544a9eb967e4448636c
> 
> Note that if you enable the C gear again, the freeze can also happen again.

@RSDuck Alright, I had to install a GCC compiler to compile the c-code Nadia so nicely wrote. I am not so keen on C programming as you'll see. However, my issue has not been resolved as for now. MelonDS says "Fails to load state" whenever i attempt to load the "fixed" gamestate. The following outlines  my steps:

In the command window:
1) "gcc fix-pokemon-state.c" to create an executable file "a.exe"
2) Rename my save state from "pkmn black 2 new.ml1" to "tobefixed.m1" (I know, the rom I have was named that way)
3)  Compile "a tobefixed.m1" to produces a new file "tobefixed.m1.fixed" with a slightly changed filesize from 6878kb to 6904kb
4) Rename "tobefixed.m1.fixed" to "pkmn black 2 new.ml1" to have melonDS recognize the save state (otherwise it doesn't).
5) Attempt to load the new .ml1 file in melonDS -- to no result: "Fails to load state"

**Comment by AaronPenders** [comment]
@RSDuck @nadiaholmquist Some feedback would be appreciated, no rush though, thanks!

**Comment by nadiaholmquist** [comment]
[fixed.zip](https://github.com/Arisotura/melonDS/files/9275029/fixed.zip)

**Comment by LeMonke6969** [comment]
> From here on out, never turn on the C-Gear in the game until their melonDS port is updated.

When the port is updated will my savestate be automatically fixed?
If so when can I expect the update to come?

**Comment by LeMonke6969** [comment]
> [fixed.zip](https://github.com/Arisotura/melonDS/files/9275029/fixed.zip)

I don't know anything about coding or how emulating works.
I would like to emulate pokemon black on my phone without having to learn coding.
If someone could fix my savestate for me it would be much appreciated, this way I won't have to restart the whole game.
Heres the save file compressed as a zip.
[pokemon black savestate.zip](https://github.com/Arisotura/melonDS/files/9305274/pokemon.black.savestate.zip)

**Comment by LeMonke6969** [comment]
> > yes this is the same issue. Nadia has put together a tool for fixing savestates: https://gist.github.com/nadiaholmquist/a90e5810ddb27544a9eb967e4448636c
> > Note that if you enable the C gear again, the freeze can also happen again.
> 
> @RSDuck @nadiaholmquist Alright, I had to install a GCC compiler to compile the c-code Nadia so nicely wrote. I am not so keen on C programming as you'll see. However, my issue has not been resolved as for now. MelonDS says "Fails to load state" whenever i attempt to load the "fixed" gamestate. The following outlines my steps:
> 
> In the command window:
> 
> 1. "gcc fix-pokemon-state.c" to create an executable file "a.exe"
> 2. Rename my save state from "pkmn black 2 new.ml1" to "tobefixed.m1" (I know, the rom I have was named that way)
> 3. Compile "a tobefixed.m1" to produces a new file "tobefixed.m1.fixed" with a slightly changed filesize from 6878kb to 6904kb
> 4. Rename "tobefixed.m1.fixed" to "pkmn black 2 new.ml1" to have melonDS recognize the save state (otherwise it doesn't).
> 5. Attempt to load the new .ml1 file in melonDS -- to no result: "Fails to load state"
> 
> If you want to have a go, I'll leave my original unfixed save state here: [pkmn black 2 new.zip](https://github.com/Arisotura/melonDS/files/9240659/pkmn.black.2.new.zip)
> 
> Thanks for your answers!

Nevermind, I followed this guy's steps and I was able to fix my file and turn off c gear.
Along the  way I learned a little bit about how to use the command prompt for programming.
Thank you melonds for forcing me to learn some comp sci, it will probably end up helping me at some point in life.

**Comment by MindlessReader** [comment]
I'm having this issue as well, I'm on 0.9.1 because newer versions don't seem to recognize the rom hack version of pokemon black I'm playing. I tried running that code on my save state, but I ran into that "State load failed" issue. I saw @nadiaholmquist was able to fix someone else's savestate when they had the same issue with fixing it, so maybe it's an issue with my system or something? Not really sure, if someone could take a look at it I'd appreciate it. 

[brokenstate.zip](https://github.com/melonDS-emu/melonDS/files/11305303/brokenstate.zip)

**Comment by SrKob** [comment]
@nadiaholmquist It's there a new solution for this? I got the same problem as the original post but in 0.9.5. 
I tried using the code linked above but MelonDs doesn't recognize the fixed savestate (The "State load failed" message shows up)- I don't know if it's due version differences or I'm doing something wrong :c

Here's the savestate if someone can wonder what went wrong.

[PNgr-espa-f.zip](https://github.com/melonDS-emu/melonDS/files/11521426/PNgr-espa-f.zip)

**Comment by RSDuck** [comment]
you didn't get the issue in 0.9.5. Based on the size of your savestate you were playing using 0.9.3. Once the savestate is fixed you need to load it again in the same version you created it, then save in game and then move to the newer version.

**Comment by SrKob** [comment]
> you didn't get the issue in 0.9.5. Based on the size of your savestate you were playing using 0.9.3. Once the savestate is fixed you need to load it again in the same version you created it, then save in game and then move to the newer version.

@RSDuck You're right! Somehow I've confused newer version with other that already had on my PC.  Sorry for the confusion :c Now I've fixed it, thank you!

**Comment by joojitor** [comment]
Im having the same issue, but i have no idea how to use Git or GCC? can somebody help me fix my savestate? i would really appreciate it ToT 
[Pokemon - White Version (USA, Europe) (NDSi Enhanced) (2).zip](https://github.com/melonDS-emu/melonDS/files/12384769/Pokemon.-.White.Version.USA.Europe.NDSi.Enhanced.2.zip)

**Comment by sceneMQU** [comment]
I have a similar but slightly different situation. Same sort of game issue,  except I was running on a version of melonDS for the [Nintendo Switch](https://github.com/RSDuck/melonDS/releases), which I believe has been forked from version 0.9.2 of the official melonDS. I say this, because when I transfer my save state from my switch to my computer, all versions of melonDS fail to load the state, however ver 0.9.2 does display the text 'State loaded from slot 2', and then after about a second the emulator closes all windows and presumably crashes. So it looks the most promising. Additionally, the dates of release for each version line up the closest.

When I attempt to execute the code offered by  @nadiaholmquist It does generate a new file, but of the same size, and this file fails to load in both my PC, and switch version of the emulator, so I believe something is being corrupted. Is anyone able to take a look and give me a hand?

[broken_save_file.zip](https://github.com/melonDS-emu/melonDS/files/13869116/broken_save_file.zip)

**Comment by deejayen** [comment]
I am also having the same issue. whenever i try to save or talk to npcss in trainer institute or subway, game freezes. i am using melonds from delta emulator.
[079F8DCC-C231-4E85-8511-9B8FDF4C5621savebroken.zip](https://github.com/melonDS-emu/melonDS/files/15051862/079F8DCC-C231-4E85-8511-9B8FDF4C5621savebroken.zip)

**Comment by nadiaholmquist** [comment]
[statefixed.zip](https://github.com/melonDS-emu/melonDS/files/15055808/statefixed.zip)
Here
Don't enable C-Gear ever again please

**Comment by ChiefChriss** [comment]
@nadiaholmquist i just encountered this issue in delta for ios, this is my save file if you could pls fix. I tried using ur fix but when i tried to use it , it would fail. sorry to bother you 
[3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip](https://github.com/melonDS-emu/melonDS/files/15057364/3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip)

**Comment by xenotwl** [comment]
you should report that to delta team not melon delta uses a old melon core delta problem not melon

**Comment by ChiefChriss** [comment]
> you should report that to delta team not melon delta uses a old melon core delta problem not melon
 real. But since it does use melon i wanted to get some type of help in this discussion since it is an old issue and there seems to be a way to fix the data.

**Comment by nadiaholmquist** [comment]
[3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip](https://github.com/melonDS-emu/melonDS/files/15057435/3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip)

**Comment by scarbcys** [comment]
> [3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip](https://github.com/melonDS-emu/melonDS/files/15057435/3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip)

I'm sorry to bug you, but I have a broken save file and I was wondering how do I export it? I can't find any information on creating a zip file from it. I'm on iOS.

**Comment by scarbcys** [comment]
> > [3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip](https://github.com/melonDS-emu/melonDS/files/15057435/3C67F9C7-9DB7-436A-A7F9-43B7D3872F57.zip)
> 
> I'm sorry to bug you, but I have a broken save file and I was wondering how do I export it? I can't find any information on creating a zip file from it. I'm on iOS.

I got this, and I have the zip file now. If anyone out there still has the ability to fix save states, would be greatly appreciated. 
[pokemonwhitesave.zip](https://github.com/melonDS-emu/melonDS/files/15085035/pokemonwhitesave.zip)

**Comment by nadiaholmquist** [comment]
[7CF08CAB-2A78-4918-A758-E5E9C9D60DAF.zip](https://github.com/melonDS-emu/melonDS/files/15093781/7CF08CAB-2A78-4918-A758-E5E9C9D60DAF.zip)
This might not work, but let's try.

**Comment by sceneMQU** [comment]
Hey Nadia, are you able to explain your process? I'd love to understand what tools you're using and how you're able to interpret the information contained in each save-state or save file. If it's too much hassle it's no worries.

**Comment by sceneMQU** [comment]
I'm quite interested in that first bit, is there somewhere I can find out more information?

> So Generic did the actual research about what goes wrong and noted down what was needed to fix someone's save state if they encountered this issue.

I'm quite interested in this part, is there somewhere I can find out more information?

**Comment by nadiaholmquist** [comment]
He did explain it but I can't say I actually remember the details, other than it being about the ARM7 getting hung up because a Wi-Fi power management register was not responding as it should. You'd have to ask him if you want the full details.

**Comment by sceneMQU** [comment]
What's their profile details? Or are they not on github? Sorry I'm just a bit confused about who Generic is.

**Comment by nadiaholmquist** [comment]
Generic is RSDuck.

If you join the Discord you can probably also find the explanation in the backlog.

**Comment by scarbcys** [comment]
> So Generic did the actual research about what goes wrong and noted down what was needed to fix someone's save state if they encountered this issue. I automated the process with a small program [here](https://gist.github.com/nadiaholmquist/a90e5810ddb27544a9eb967e4448636c). With the amount of people having this issue recently because of the Delta release I made a [JavaScript port](https://nhp.sh/gen5statefix/) that's usable from a web browser here so hopefully people can just fix their own saves going forward until the Delta devs get on updating their melonDS.

This worked, thank you sm for the continued support across like 2 years. <3

**Comment by longbrah** [comment]
@nadiaholmquist Hi, I've tried to use your javascript with the exported save state from my delta app but it's coming up with "Couldn't find Wi-Fi data in the save state." Is there a work around or have I missed something? Thanks

**Comment by nottatubby** [comment]
@nadiaholmquist 
Hi could you please try to fix my save file? I am also having the issue where my game freezes whenever I try to turn off the cgear.
[3D85A16A-C273-458F-9559-33D05063AF4C.zip](https://github.com/melonDS-emu/melonDS/files/15139548/3D85A16A-C273-458F-9559-33D05063AF4C.zip)

**Comment by nadiaholmquist** [comment]
[3D85A16A-C273-458F-9559-33D05063AF4C.zip](https://github.com/melonDS-emu/melonDS/files/15141702/3D85A16A-C273-458F-9559-33D05063AF4C.zip)

**Comment by Fixgen5** [comment]
Can someone explain how i can load my save file to the java script.
I make a long press on the icon of the game and choose export save files.
But when i load it to the java script it gives the message Couldn't find Wi-Fi data in the save state.

what did i do wrong?

**Comment by nadiaholmquist** [comment]
You have to find the save state (not the save file) through the Files app. I think the Delta FAQ mentions how.

**Comment by nottatubby** [comment]
> [3D85A16A-C273-458F-9559-33D05063AF4C.zip](https://github.com/melonDS-emu/melonDS/files/15141702/3D85A16A-C273-458F-9559-33D05063AF4C.zip)

When I try to put that file into my save states folder, it doesn’t show up in the actual game. Did I perhaps give you the wrong file? I also notice that this file does not have a game preview unlike the other save states? Did I perhaps give you the wrong file?

**Comment by Snowman293** [comment]
A big thank you to the admin here. I was having a hard time finding a solution because this suddenly happened, and it worked out right here. Have a nice day.

**Comment by Otterh4** [comment]
![00FCFA38-D4E8-4C44-801E-8BD3CCAD1A04](https://github.com/melonDS-emu/melonDS/assets/168789964/5e7d73f3-452b-40a0-9998-72769ae617c5)

Is this file able to be fixed? The web fix doesn’t work on it.

**Comment by Otterh4** [comment]
I keep freezing on ferris wheel.
[00FCFA38-D4E8-4C44-801E-8BD3CCAD1A04.zip](https://github.com/melonDS-emu/melonDS/files/15195110/00FCFA38-D4E8-4C44-801E-8BD3CCAD1A04.zip)

**Comment by AlexHomeyer** [comment]
> > So Generic did the actual research about what goes wrong and noted down what was needed to fix someone's save state if they encountered this issue. I automated the process with a small program [here](https://gist.github.com/nadiaholmquist/a90e5810ddb27544a9eb967e4448636c). With the amount of people having this issue recently because of the Delta release I made a [JavaScript port](https://nhp.sh/gen5statefix/) that's usable from a web browser here so hopefully people can just fix their own saves going forward until the Delta devs get on updating their melonDS.
> 
> This worked, thank you sm for the continued support across like 2 years. <3

Hey nadia, I am having the same issue where I am stuck at the ferris wheel and I can’t save or turn the CGear off without the game freezing. I used your web port and I downloaded what I assume is the fixed save state, but I can’t figure out how to place that fixed save state back into the Delta app. Any help would be greatly appreciated!

**Comment by nadiaholmquist** [comment]
What you need to do is place that file you downloaded in exactly the same place as the save state you uploaded, with the exact same file name, and it should then load it.

**Comment by AlexHomeyer** [comment]
> What you need to do is place that file you downloaded in exactly the same place as the save state you uploaded, with the exact same file name, and it should then load it.

I figured it out thank you so much!

**Comment by ranveerdhaliwal03** [comment]
hey im also stuck at the ferris wheel part on Delta. 
[F7FA5D4F-D818-47FB-A027-4C9F5C5CCC6B.zip](https://github.com/melonDS-emu/melonDS/files/15284031/F7FA5D4F-D818-47FB-A027-4C9F5C5CCC6B.zip)

**Comment by nadiaholmquist** [comment]
https://github.com/melonDS-emu/melonDS/issues/2026

**Comment by Romann1333** [comment]
@nadiaholmquist  
Hi, I play this game since 1week and I discover this freeze. 
I’m on IOS with no PC and I dont know how to put my save here for go thro this freeze. 
Sorry for bother you, I hope i will have solution.

**Comment by arielbensorek** [comment]
Would it be easy to implement a fix for Gen 4 too (HG/SS)? 
The JavaScript from #2026 correctly identifies save states that are experiencing this same issue (caused by trying to use Wi-Fi features), but its output does not fix the issue.

**Comment by nadiaholmquist** [comment]
Delta is updating their melonDS core, so I don't think there is much point in working on that save state fixing script any further.

**Comment by picciottino** [comment]
Hello! I'm using melonDS via RetroArch on a SteamDeck. How do I fix this issue? Thanks :)
